### ISSUE TITLE
No key events with Qt 5.9

### ISSUE THREAD

**Issue by cranes-bill** [joseriosneto/qupzilla-vimplugin#13] opened 2017-06-22 13:05 UTC
Hi!
I successfully compilled and installed the plugin for **QupZilla branch V2.0**, but i'm not able to activate it. There is no error on the console. What might be the reason?
Sorry for the bad English!

![capture du 2017-06-22 15 49 50](https://user-images.githubusercontent.com/5161278/27435173-ff8dc8d8-5763-11e7-98ea-56db489e948d.png)

**Comment by joseriosneto** [comment] 2017-06-22 14:25
Hi @cranes-bill. No worries about the English. The last version I managed to work was v2.1.0 but I don't remember why it didn't work on v2.0. Currently I can't compile QupZilla below commit efc4725e because of openssl. I can give a try later. Which OS are you using?

**Comment by cranes-bill** [comment] 2017-06-22 15:43
OK, thanks! Don't worry, _QupZilla v2.0_ is not maintained anymore, so you don't have to investigate the problem.
I'm using _CentOS 7_ where _Qt 5.6.1_ is the default Qt version and _QupZilla v2.0_ is the max version where can be compiled with that Qt version. But i also tried with _QupZilla master_ and _Qt 5.9_ [(official precompiled release](http://download.qt.io/official_releases/qt/5.9/5.9.0/), _due to i'm lazy to compile it myself_), and the plugin is loaded, but i can't get any action with the keys. Perhaps i'm missing something!?
[Here](https://yadi.sk/d/XuPnHb9b3KN5HL) is the Appimage with these Qt libraries and Vimplugin included, where i've been using for testing (_in case you want to look on it_).

**Comment by joseriosneto** [comment] 2017-06-22 19:03
No, you're not missing anything. I am also experiencing this since I updated my environment to qt5-webengine 5.9.0-1 (I'm on Arch).

Since you're familiar with QupZilla's code I will dig a bit further here. I am working on QupZilla's master `d6b142bba`. 

A quick debug shows the plugin is not receiving keyPress events anymore from QupZilla (it does receives keyRelease events though). At `WebView::eventFilter` the keyPress events are being delivered to `m_rwhvqt` object and not `parentWidget()`. The thing is, QupZilla only let plugins process events delivered to `parentWidget` and not `m_rwhvqt` which I am still unsure how it's used. 

A quick hack to make it work is changing the line 1314 at webview.cpp in QupZilla's code:

>-if (obj == parentWidget()) {
>+if (obj == parentWidget() || obj == m_rwhvqt) {

This will forward these events to plugins. I will debug a bit more to understand why this changed. Anyway I'll file a bug in QupZilla where we can discuss this further.

**Comment by joseriosneto** [comment] 2017-06-22 20:02
FYI

QupZilla/qupzilla#2369

**Comment by cranes-bill** [comment] 2017-06-23 04:39
OK, thanks!
You might close the issue, if needed.

**Comment by joseriosneto** [comment] 2017-06-23 10:23
I'll add a note in the README about this. While we don't have a fix for this I believe it's good to keep this issue opened. Thanks for finding this.

**Comment by joseriosneto** [comment] 2017-06-24 21:22
I just confirmed it works with qtwebengine 5.8.

**Comment by cranes-bill** [comment] 2017-06-25 05:18
> I just confirmed it works with qtwebengine 5.8.

Yes, i also can confirm that.

**Comment by joseriosneto** [comment] 2017-06-25 10:54
QTBUG:
https://bugreports.qt.io/browse/QTBUG-61621

**Comment by joseriosneto** [comment] 2017-08-19 23:26
Fixed in Qt 5.9.2.

**Closed by joseriosneto** 2017-08-19 23:26 UTC
Labels: qtwebengine
